[metadata]
name = "Generic"
version = "1.0.0"
aliases = ["generic", "unknown"]
description = "Generic SQL dialect fallback"
min_version = ""
max_version = ""

[detection]
connection_patterns = []
driver_patterns = []

[features]
supports_transactions = true
supports_savepoints = false
supports_schemas = false
supports_sequences = false
supports_arrays = false
case_sensitive = false

[sql]
quote_identifier = "\""
escape_identifier = "\"\""
current_timestamp = "CURRENT_TIMESTAMP"
boolean_true = "TRUE"
boolean_false = "FALSE"

[types]
migration_id = "VARCHAR(255)"
migration_type = "VARCHAR(16)"
version = "INTEGER"
filename = "VARCHAR(255)"
checksum = "VARCHAR(64)"
applied_at = "TIMESTAMP"
execution_time_ms = "INTEGER"
success = "BOOLEAN"