[metadata]
name = "PostgreSQL"
version = "1.0.0"
aliases = ["postgres", "postgresql", "pg"]
description = "PostgreSQL database dialect support"
min_version = "9.0"
max_version = "16.x"

[detection]
connection_patterns = [
    "postgresql://.*",
    "postgres://.*", 
    ".*postgresql.*",
    ".*postgres.*"
]
driver_patterns = [
    "PostgreSQL.*",
    "psqlODBC.*"
]

[features]
supports_transactions = true
supports_savepoints = true
supports_schemas = true
supports_sequences = true
supports_arrays = true
case_sensitive = false

[sql]
quote_identifier = "\""
escape_identifier = "\"\""
current_timestamp = "CURRENT_TIMESTAMP"
boolean_true = "TRUE"
boolean_false = "FALSE"

[types]
migration_id = "VARCHAR(255)"
migration_type = "VARCHAR(16)"
version = "INTEGER"
filename = "VARCHAR(255)"
checksum = "VARCHAR(64)"
applied_at = "TIMESTAMP"
execution_time_ms = "INTEGER"
success = "BOOLEAN"